### ISSUE TITLE
ProgramInvocationException when trying to run locally

### ISSUE THREAD

**Issue by dvellanki** [OHNLP/OHNLPTK_SETUP#4]
Hi Andrew,
When I try to run the run_pipeline_local script after making the required configuration changes, I keep getting the following errors. 
Appreciate any pointers on resolution for the below.

**Installations:**
Backbone  - [v3.0.26]
Configurator - [v1.0.17]
Medtagger -[v1.0.81]
Flink - [1.18.0]

**Exception:**
Flink Cluster Started - Job Progress Can be Seen via Configured WebUI Port (Default: localhost:8081)
Submitting Job...

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: org.ohnlp.backbone.api.exceptions.ComponentInitializationException: org.ohnlp.backbone.api.exceptions.ComponentInitializationException: com.microsoft.sqlserver.jdbc.SQLServerException: A processing error "Incorrect syntax near '10'." occurred.
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:105)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:851)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:245)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1095)
        at org.apache.flink.client.cli.CliFrontend.lambda$mainInternal$9(CliFrontend.java:1189)
        at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
        at org.apache.flink.client.cli.CliFrontend.mainInternal(CliFrontend.java:1189)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1157)

**Comment by qqndrew** [comment]
Hello,
This error suggests that your SQL syntax is incorrect ("Incorrect syntax near '10'"), you will want to double check that within any steps that use SQL.

Thanks,
Andrew

**Comment by dvellanki** [comment]
Thank You, Andrew. resolved it. There was an error in the SQL syntax that I was using.
